image:
  name: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build and publish docker image.
        services:
          - docker # Enable Docker for your repository
        script:
          - apt-get update && apt-get install -y awscli
          # Modify the commands below to build your repository.
          # Set the name of the docker image we will be building.
          - export IMAGE_NAME="666624136412.dkr.ecr.us-east-1.amazonaws.com/igetulio-prd:latest"
          # Build the docker image and push to Dockerhub.
          - docker build -t "$IMAGE_NAME" .
          - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 666624136412.dkr.ecr.us-east-1.amazonaws.com
          - docker push "$IMAGE_NAME"
    - step:
        name: Deploy to ECS
        script:
          # Replace the docker image name in the task definition with the newly pushed image.
          - export IMAGE_NAME="666624136412.dkr.ecr.us-east-1.amazonaws.com/igetulio-prd:latest"
          - envsubst < task-definition-template.json >  task-definition.json

          # Update the task definition.
          - pipe: atlassian/aws-ecs-deploy:1.0.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: "cactoweb-prd-cluster"
              SERVICE_NAME: "igetulio-admin-prd"
              TASK_DEFINITION: "task-definition.json"
